# Generated by Django 4.1.2 on 2022-11-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='status',
            field=models.SmallIntegerField(),
        ),
    ]
