# Generated by Django 4.1.2 on 2022-11-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_coffee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '下架'), (1, '上架')], default=1),
        ),
    ]
