# Generated by Django 4.1.2 on 2022-11-29 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafe', '0003_alter_coffee_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee', models.ManyToManyField(related_name='coffee', to='cafe.coffee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redeem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
